// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdglhbwwvwkojjdrrsga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkZ2xoYnd3dndrb2pqZHJyc2dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MTI3NjAsImV4cCI6MjA2OTM4ODc2MH0.nfEZi4flk5-15K5DmgFdgZscaoOI44CIR9S1-BHXhvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});