// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuqrsarjxcbdxckyuqnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1cXJzYXJqeGNiZHhja3l1cW5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwNjQzMDIsImV4cCI6MjA5MTY0MDMwMn0.kotASsigrqh4998fTseANc8MwI29xrwAhl6BcgrCbkE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});